GTA = rea.csv("mvtWeek1.csv")
GTA = read.csv("mvtWeek1.csv")
str(GTA)
summary(GTA)
min(GTA$ID)
max(GTA$ID)
min(GTA$Beat)
True_Arrests = subset(GTA, Arrest == TRUE)
nrow(True_Arrests)
match("ALLEY", GTA$LocationDescription)
summary(GTA$LocationDescription)
?match
nrow(GTA$LocationDescription)
LocationDescription = subset(GTA, LocationDescription)
hist(GTA$LocationDescription)
LocationDescription = subset(GTA, LocationDescription == "ALLEY")
nrow(LocationDescription)
LocationDescription = subset(GTA, match("ALLEY", GTA$LocationDescription))
LocationDescription = subset(GTA, LocationDescription == "ALLEY")
nrow(LocationDescription)
summar(GTA$Date)
summary(GTA$Date)
DateConvert = as.Date(strptime(mvt$Date, "%m/%d/%y %H:%M"))
DateConvert = as.Date(strptime(GTA$Date, "%m/%d/%y %H:%M"))
summary(GTA$Date)
summary(DateConvert)
median(DateConvert)
GTA$month = months(DateConvert)
GTA$WeekDays = weekdays(DateConvert)
GTA$Month = months(DateConvert)
summary(GTA)
str(GTA)
GTA$month = NULL
str(GTA)
summary(GTA)
summary(GTA$Date)
GTA$Date = DateConvert
summary(GTA$Date)
str(GTA$Month)
str(GTA$WeekDays)
Summary(GTA$Month)
Summary(GTA$Month)
summary(GTA$Month)
table(GTA$Date)
summary(GTA)
summary(True_Arrests)
True_Arrests = subset(GTA, Arrest == TRUE)
summary(True_Arrests)
table(True_Arrests)
table(True_Arrests$Month)
summary(True_Arrests$Month)
?table
hist(True_Arrests$Month)
summary(DateConvert)
GTA$Month = months(DateConvert)
GTA$WeekDay = weekdays(DateConvert)
summary(GTA)
str(GTA)
GTA$WeekDays = NULL
str(GTA)
summary(GT)
summary(GTA)
GTA_TrueArrest = subset(GTA, Arrest == TRUE)
summary(GTA_TrueArrest)
str(GTA_TrueArrest)
table(GTA_TrueArrest)
table(GTA_TrueArrest$Month)
nrow(subset(GTA_TrueArrest, Month == "January"))
table(GTA$Month)
table(GTA$WeekDay)
hist(GTA$Date)
hist(GTA$Date, breaks = 100)
boxplot(GTA$Date)
boxplot(subset(GTA$Date, Arrest == TRUE))
boxplot(GTA_TrueArrest$Date)
GTA$Year = years(DateConvert)
GTA$Year = year(DateConvert)
GTA_2001 = subset(GTA, Date == "2001")
GTA_2001 = subset(GTA, Date == 2001)
summary(GTA_2001)
str(GTA_2001)
GTA_2001 = subset(GTA, Date >= 01-01-2001 && Date <= 12-31-2001)
str(GTA_2001)
GTA_2001 = subset(GTA, Date >= "01-01-2001" && Date <= "12-31-2001")
summary(GTA)
str(GTA)
GTA_2001 = subset(GTA, Date >= "2001-01-01" && Date <= "2001-12-31")
str(GTA_2001)
GTA_2001 = subset(GTA, Date >= 2001-01-01 && Date <= 2001-12-31)
str(GTA_2001)
GTA_2001 = subset(GTA, Date >= as.Date("2001-01-01") && Date <= as.Date("2001-12-31"))
str(GTA_2001)
str(GT)
str(GTA)
GTA_2001 = subset(GTA, Date >= as.Date("2001-01-01") && Date <= as.Date("2001-12-31"))
str(GTA_2001)
summart(GTA$Date)
summary(GTA$Date)
GTA_2001 = subset(GTA, Date >= as.Date("2001-01-01"))
str(GTA_2001)
GTA_2001 = subset(GTA, Date <= as.Date("2001-01-01"))
str(GTA_2001)
GTA_2001 = subset(GTA, Date <= as.Date("2001-01-31"))
str(GTA_2001)
GTA_2001_TrueArrest = subset(GTA_2001, Arrest = TRUE)
str(GTA_2001)
str(GTA_2001_TrueArrest)
GTA_2001_TrueArrest = subset(GTA_2001, Arrest == TRUE)
GTA_2001 = subset(GTA, Date <= as.Date("2001-01-31"))
str(GTA_2001)
GTA_2001_TrueArrest = subset(GTA_2001, Arrest == TRUE)
str(GTA_2001_TrueArrest)
nrow(GTA_2001_TrueArrest)/nrow(GTA_2001)
168/1517
boxplot(GTA_2001$Date)
GTA_2001 = subset(GTA, Date <= as.Date("2001-12-31"))
boxplot(GTA_2001$Date)
str(GTA_2001)
GTA_2001_TrueArrest = subset(GTA_2001, Arrest == TRUE)
nrow(GTA_2001_TrueArrest)/nrow(GTA_2001)
?subset
GTA_2001_1 = subset(GTA, Date >= as.Date("2001-01-01") & Date <= as.Date("2001-12-31"))
str(GTA_2001)
str(GTA_2001_1)
GTA_2007 = subset(GTA, Date >= as.Date("2007-01-01") & Date <= as.Date("2007-12-31"))
str(GTA_2007)
GTA_2007_TrueArrest = subset(GTA_2007, Arrest == TRUE)
nrow(GTA_2007_TrueArrest)/nrow(GTA_2007)
GTA_2012 = subset(GTA, Date >= as.Date("2012-01-01") & Date <= as.Date("2012-12-31"))
GTA_2012_TrueArrest = subset(GTA_2012, Arrest == TRUE)
nrow(GTA_2012_TrueArrest)/nrow(GTA_2012)
sort(table(GTA$LocationDescription))
GTA_LocationDescription = subset(GTA, LocationDescription == "GAS STAION" | LocationDescription == "STREET" | LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)" | LocationDescription == "ALLEY" | LocationDescription == "DRIVEWAY - RESIDENTIAL")
str(GTA_LocationDescription)
GTA_LocationDescriptionTop5 = subset(GTA, LocationDescription == "GAS STAION" | LocationDescription == "STREET" | LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)" | LocationDescription == "ALLEY" | LocationDescription == "DRIVEWAY - RESIDENTIAL")
GTA_LocationDescriptionTop_1 = subset(GTA, LocationDescription == "STREET")
str(GTA_LocationDescriptionTop_1)
GTA_LocationDescriptionTop_1 = subset(GTA, LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)")
GTA_LocationDescriptionTop_1 = subset(GTA, LocationDescription == "STREET")
GTA_LocationDescriptionTop_2 = subset(GTA, LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)")
GTA_LocationDescriptionTop_3 = subset(GTA, LocationDescription == "ALLEY")
GTA_LocationDescriptionTop_4 = subset(GTA, LocationDescription == "GAS STATION")
GTA_LocationDescriptionTop_5 = subset(GTA, LocationDescription == "DRIVEWAY - RESIDENTIAL")
?rbind
rbind(GTA_LocationDescriptionTop_1,GTA_LocationDescriptionTop_2,GTA_LocationDescriptionTop_3,GTA_LocationDescriptionTop_4,GTA_LocationDescriptionTop_5)
GTA_LocationDescriptionRbindTop5 = rbind(GTA_LocationDescriptionTop_1,GTA_LocationDescriptionTop_2,GTA_LocationDescriptionTop_3,GTA_LocationDescriptionTop_4,GTA_LocationDescriptionTop_5)
str(GTA_LocationDescriptionTop5)
str(GTA_LocationDescriptionRbindTop5)
str(GTA_LocationDescriptionTop5)
GTA_LocationDescriptionTop5 = subset(GTA, LocationDescription == "GAS STAION" | LocationDescription == "STREET" | LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)" | LocationDescription == "ALLEY" | LocationDescription == "DRIVEWAY - RESIDENTIAL")
sort(table(GTA$LocationDescription))
GTA_LocationDescriptionTop5 = subset(GTA, LocationDescription == "GAS STAION" | LocationDescription == "STREET" | LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)" | LocationDescription == "ALLEY" | LocationDescription == "DRIVEWAY - RESIDENTIAL")
156564 + 14852 + 2308 + 2111 + 1675167516751675
156564 + 14852 + 2308 + 2111 + 1675
str(GTA_LocationDescriptionRbindTop5)
GTA_LocationDescriptionTop5 = subset(GTA, LocationDescription == "GAS STAION" | LocationDescription == "STREET" | LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)" | LocationDescription == "ALLEY" | LocationDescription == "DRIVEWAY - RESIDENTIAL")
str(GTA_LocationDescriptionTop5)
nrow(subset(GTA, LocationDescription == "GAS STAION"))
nrow(GTA_LocationDescriptionTop_1)
GTA_LocationDescriptionTop_1 = subset(GTA, LocationDescription == "STREET")
nrow(GTA_LocationDescriptionTop_1)
nrow(subset(GTA, LocationDescription == "GAS STAION"))
nrow(GTA_LocationDescriptionTop_4)
GTA_LocationDescriptionTop_4 = subset(GTA, LocationDescription == "GAS STATION")
nrow(GTA_LocationDescriptionTop_4)
GTA_LocationDescriptionT = subset(GTA, LocationDescription == "STREET")
nrow(GTA_LocationDescriptionT)
GTA_LocationDescriptionT = subset(GTA, LocationDescription == "STREET" | LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)")
nrow(GTA_LocationDescriptionT)
GTA_LocationDescriptionT = subset(GTA, LocationDescription == "STREET" | LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)" |LocationDescription == "GAS STAION")
nrow(GTA_LocationDescriptionT)
GTA_LocationDescriptionT = subset(GTA, LocationDescription == "STREET" | LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)" |LocationDescription == "GAS STATION")
nrow(GTA_LocationDescriptionT)
GTA_LocationDescriptionTop5 = subset(GTA, LocationDescription == "GAS STATION" | LocationDescription == "STREET" | LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)" | LocationDescription == "ALLEY" | LocationDescription == "DRIVEWAY - RESIDENTIAL")
nrow(GTA_LocationDescriptionTop5)
table(GTA_LocationDescriptionTop5$LocationDescription)
str(GTA_LocationDescriptionTop5)
GTA_LocationDescriptionTop5$LocationDescription = factor(GTA_LocationDescriptionTop5$LocationDescription)
str(GTA_LocationDescriptionTop5)
Top5 = (GTA_LocationDescriptionTop5)
str(Top5))
str(Top5)
Top5_TrueArrest = subset(Top5, Arrest ==TRUE)
str(Top5_TrueArrest)
L1 = subset(Top5_TrueArrest, LocationDescription == "STREET")
L2 = subset(Top5_TrueArrest, LocationDescription == "GAS STATION")
L3 = subset(Top5_TrueArrest, LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)")
L3 = subset(Top5_TrueArrest, LocationDescription == "DRIVEWAY - RESIDENTIAL")
L3 = subset(Top5_TrueArrest, LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)")
L4 = subset(Top5_TrueArrest, LocationDescription == "DRIVEWAY - RESIDENTIAL")
L5 = subset(Top5_TrueArrest, LocationDescription == "ALLEY")
str(L1)
str(L2)
str(L3)
str(L4)
str(L5)
Top5_TrueArrest = subset(Top5, Arrest ==FALSE)
Top5_TrueArrest = subset(Top5, Arrest ==TRUE)
Top5_FalseArrest = subset(Top5, Arrest ==FALSE)
str(Top5_FalseArrest)
str(Top5_TrueArrest)
GTA_LocationDescriptionT = subset(GTA, LocationDescription == "STREET")
nrow(GTA_LocationDescriptionT)
nrow(GTA_LocationDescriptionTop_4)
GTA_LocationDescriptionTop_4 = subset(GTA, LocationDescription == "GAS STATION")
nrow(GTA_LocationDescriptionTop_4)
GTA_LocationDescriptionTop_2 = subset(GTA, LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)")
str(GTA_LocationDescriptionTop_2)
GTA_LocationDescriptionTop_5 = subset(GTA, LocationDescription == "DRIVEWAY - RESIDENTIAL")
str(GTA_LocationDescriptionTop_5)
GTA_LocationDescriptionTop_3 = subset(GTA, LocationDescription == "ALLEY")
str(GTA_LocationDescriptionTop_4)
GTA_LocationDescriptionTop_4 = subset(GTA, LocationDescription == "GAS STATION")
str(GTA_LocationDescriptionTop_4)
GTA_LocationDescriptionTop_3 = subset(GTA, LocationDescription == "ALLEY")
str(GTA_LocationDescriptionTop_3)
11595/156564
439/2111
1603/14852
132/1675
249/2308
GTA_GS = subset(GTA, LocationDescription == "GAS STATION")
table(GTA_GS$WeekDay)
GTA_RD = subset(GTA, LocationDescription == "DRIVEWAY - RESIDENTIAL")
table(GTA_RD$WeekDay)
savehistory("~/Projects/edx/AnalyticsEdge_MITx15_071x/lec1/HW1_1.R")
