plot(CC$Date, CC$StockPrice, xlab="Date", ylab="StockPrice")
line(PG$Date, PG$StockPrice, xlab="Date", ylab="StockPrice")
line(PG$Date, PG$StockPrice)
lines(PG$Date, PG$StockPrice)
plot(CC$Date, CC$StockPrice, xlab="Date", ylab="StockPrice", col="blue")
plot(CC$Date, CC$StockPrice, xlab="Date", ylab="StockPrice", col="red")
lines(PG$Date, PG$StockPrice, col="red")
lines(PG$Date, PG$StockPrice, col="bue")
lines(PG$Date, PG$StockPrice, col="blue")
abline(v=as.Date(c("2000-01-01")), lwd=2)
abline(v=as.Date(c("2000-12-01")), lwd=2)
abline(v=as.Date(c("1983-01-01")), lwd=2)
abline(v=as.Date(c("1983-12-01")), lwd=2)
lines(CC$Date, CC$StockPrice, col="red")
lines(CC$Date, CC$StockPrice, col="red")
plot(CC$Date, CC$StockPrice, xlab="Date", ylab="StockPrice", col="red")
abline(v=as.Date(c("1983-01-01")), lwd=2)
abline(v=as.Date(c("1983-12-01")), lwd=2)
lines(CC$Date, CC$StockPrice, col="red")
lines(PG$Date, PG$StockPrice, col="blue")
plot(CocaCola$Date[301:432], CocaCola$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
plot(CC$Date[301:432], CC$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
lines(PG$Date, PG$StockPrice, col="blue")
lines(IB$Date, IBM$StockPrice, col="green")
lines(IBM$Date, IBM$StockPrice, col="green")
lines(B$Date, B$StockPrice, col="yellow")
lines(GE$Date, GE$StockPrice, col="black")
colors()
abline(v=as.Date(c("2000-01-01")), lwd=2)
abline(v=as.Date(c("2000-12-01")), lwd=2)
abline(v=as.Date(c("1995-01-01")), lwd=2)
abline(v=as.Date(c("2005-12-31")), lwd=2)
abline(v=as.Date(c("1997-09-01")), lwd=2)
abline(v=as.Date(c("1997-11-31")), lwd=2)
abline(v=as.Date(c("1997-11-30")), lwd=2)
plot(CocaCola$Date[301:432], CocaCola$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
plot(CC$Date[301:432], CC$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
abline(v=as.Date(c("1997-11-31")), lwd=1)
abline(v=as.Date(c("1997-11-30")), lwd=2)
abline(v=as.Date(c("1997-09-01")), lwd=2)
lines(PG$Date, PG$StockPrice, col="blue")
lines(IB$Date, IBM$StockPrice, col="green")
lines(IBM$Date, IBM$StockPrice, col="green")
lines(B$Date, B$StockPrice, col="yellow")
abline(v=as.Date(c("1997-09-01")), lwd=2)
abline(v=as.Date(c("1997-09-01")), lwd=2)
lines(GE$Date, GE$StockPrice, col="black")
abline(v=as.Date(c("2004-09-01")), lwd=2)
abline(v=as.Date(c("2004-01-01")), lwd=2)
abline(v=as.Date(c("2005-12-31")), lwd=2)
summary(IBM)
?tapply
tapply(IBM, months(IBM$Date))
tapply(IBM$StockPrice, months(IBM$Date))
tapply(IBM$StockPrice, months(IBM$Date), mean)
summary(IBM$StockPrice)
lines(IBM$Date, IBM$StockPrice, col="green")
lines(IBM$Date, IBM$StockPrice, col="green")
plot(IBM$Date, IBM$StockPrice, col="green")
monthlyMeans = tapply(IBM$StockPrice, months(IBM$Date), mean)
monthlyMeans
summary(monthlyMeans)
sort(monthlyMeans)
tapply(GE$StockPrice, months(GE$Date), mean)
tapply(CC$StockPrice, months(CC$Date), mean)
tapply(GE$StockPrice, months(GE$Date), mean)
tapply(CC$StockPrice, months(CC$Date), mean)
tapply(PG$StockPrice, months(PG$Date), mean)
tapply(B$StockPrice, months(B$Date), mean)
GE_Monthly = tapply(GE$StockPrice, months(GE$Date), mean)
B_Monthly = tapply(B$StockPrice, months(B$Date), mean)
PG_Monthly = tapply(PG$StockPrice, months(PG$Date), mean)
CC_Monthly = tapply(CC$StockPrice, months(CC$Date), mean)
summary(GE_Monthly)
summary(B_Monthly)
summaryPG_Monthly)
summary(PG_Monthly)
summary(CC_Monthly)
savehistory("~/Projects/edx/AnalyticsEdge_MITx15_071x/lec1/HW1_2.R")
