
CPS = read.csv("CPSData.csv")
MAC = read.csv("MetroAreaCodes.csv")
CC = read.csv("CountryCodes.csv")
summary(CPS)
sort(table(CPS$Region))
sort(table(CPS$State))
summary(CPS$Citizenship)
str(CPS)
116639 + 7073 +7590
116639 + 7073
123712/131302
summary(CPS$Race)
summary(CPS$Hispanic)
str(CPS$Hispanic)
table(CPS$Hispanic)
tapply(CPS$Race, CPS$Hispanic)
table(tapply(CPS$Race, CPS$Hispanic))
summary(CPS$Race)
AI = subset(CPS, Race == "Asian" & Hispanic == 1)
summary(AI)
nrow(AI)
AI = subset(CPS, Race == "American Indian" & Hispanic == 1)
AS = subset(CPS, Race == "Asian" & Hispanic == 1)
B = subset(CPS, Race == "Black" & Hispanic == 1)
MR = subset(CPS, Race == "Multiracial" & Hispanic == 1)
PI = subset(CPS, Race == "Pacific Islander" & Hispanic == 1)
W = subset(CPS, Race == "White" & Hispanic == 1)
nrow(AI)
nrow(AS)
nrow(B)
nrow(MR)
nrow(PI)
nrow(W)
summary(CPS)
is.na(CPS$Married)
table(CPS$Region, is.na(CPS$Married))
table(CPS$Sex, is.na(CPS$Married))
table(CPS$Age, is.na(CPS$Married))
summary(CPS)
table(CPS$Citizenship, is.na(CPS$Married))
table(CPS$MetroAreaCode, is.na(CPS$Married))
summary(CPS$State)
CPS_DC = subset(CPS, State == "District of Columbia")
table(CPS_DC$MetroAreaCode, is.na(CPS_DC$Married))
table(CPS$State, is.na(CPS$MetroAreaCode))
S_MAC = table(CPS$State, is.na(CPS$MetroAreaCode))
?"["
S_MAC["Alabama"][TRUE]
S_MAC[TRE]["Alabama"]
S_MAC[TRUE]["Alabama"]
S_MAC
S_MAC = table(CPS$Region, is.na(CPS$MetroAreaCode))
table(CPS$Region, is.na(CPS$MetroAreaCode))
8084/8084
8084/25093
10674/(10674+20010)
5609/(5609+20330)
9871/(9871+31631)
8084/(8084+25093)
tapply(CPS$Race, CPS$Hispanic)
table(tapply(CPS$Race, CPS$Hispanic))
table(CPS$State, is.na(CPS$MetroAreaCode))
S_MAC = table(CPS$State, is.na(CPS$MetroAreaCode))
tapply(CPS$State, is.na(CPS$MetroAreaCode), mean)
tapply(is.na(CPS$MetroAreaCode), CPS$State, mean)
tapply(is.na(CPS$MetroAreaCode), CPS$State, mean) > 0.3
table(tapply(is.na(CPS$MetroAreaCode), CPS$State, mean) > 0.3)
summary(CPS)
max(tapply(is.na(CPS$MetroAreaCode), CPS$State, mean))
MAC_S = tapply(is.na(CPS$MetroAreaCode), CPS$State, mean))
MAC_S = tapply(is.na(CPS$MetroAreaCode), CPS$State, mean)
MAC_S
summary(MAC_S)
str(MAC_S)
summary(MAC)
summary(CC)
str(MAC)
str(CC)
CPS = merge(CPS, MetroAreaMap, by.x="MetroAreaCode", by.y="Code", all.x=TRUE)
CPS = merge(CPS, MAC, by.x="MetroAreaCode", by.y="Code", all.x=TRUE)
CPS = merge(CPS, CC, by.x="CountryCode", by.y="Code", all.x=TRUE)
summay(CPS)
summary(CPS)
CPS = merge(CPS, CC, by.x="CountryOfBirthCode", by.y="Code", all.x=TRUE)
summary(CPS)
str(CPS)
summary(CPS$MetroArea)
table(CPS$MetroArea)
sort(table(CPS$MetroArea))
tapply(CPS$Hispanic, CPS$MetroArea, mean)
sort(tapply(CPS$Hispanic, CPS$MetroArea, mean))
summary(CPS)
tapply(CPS$Race == "Asian", CPS$MetroArea, mean)
sort(tapply(CPS$Race == "Asian", CPS$MetroArea, mean))
sort(tapply(CPS$Race == "Asian", CPS$MetroArea, mean)) >= 0.2
table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean))
sort(table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean)))
sum( sort(table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean))) > 0.2)
sum( sort(table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean))) >= 0.2)
sum( tapply(CPS$Race == "Asian", CPS$MetroArea, mean) >= 0.2)
sum( table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean)) >= 0.2)
sum( table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean)))
summary(CPS$Race)
summary(CPS$MetroArea)
str(CPS$MetroArea)
sum( table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean)))
summary(CPS$Race)
Asians = subset(CPS, Race == "Asian")
nrow(Asians)
tabl(CPS$Race == "Asian")
table(CPS$Race == "Asian")
table(CPS$Race == "Asian", CPS$MetroArea)
sum( table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean)))
str(CPS$MetroArea)
str(CPS$MetroAreaCode)
summary(CPS$MetroAreaCode)
str(CPS)
sum( table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean)))
sum( table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean)) >= 0.2)
tapply(CPS$Race == "Asian", CPS$MetroArea, mean)
tapply(CPS$Race == "Asian", CPS$MetroAreaCode, mean)
sum( table(tapply(CPS$Race == "Asian", CPS$MetroAreaCode, mean)) >= 0.2)
sum(CPS$MetroAreaCode)
summary(CPS$MetroAreaCode)
summary(CPS$MetroArea)
table(CPS$MetroArea)
sum(table(CPS$MetroArea))
nrow(table(CPS$MetroArea))
sum(tapply(CPS$Race == "Asian", CPS$MetroAreaCode, mean))
sum(table(tapply(CPS$Race == "Asian", CPS$MetroAreaCode, mean)))
table(tapply(CPS$Race == "Asian", CPS$MetroAreaCode, mean))
table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean))
(tapply(CPS$Race == "Asian", CPS$MetroArea, mean))
table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean) <= 0.02)
table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean) >= 0.02)
?tapply
nrow(table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean)))
NA > 0.02
NA < 0.02
NA == FALSE
nrow(table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean, na.rm = TRUE)))
table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean, na.rm = TRUE))
table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean) >= 0.02)
table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean, na.rm = TRUE) >= 0.02)
tapply(is.na(CPS$MetroAreaCode), CPS$State, mean) > 0.3
table(tapply(is.na(CPS$MetroAreaCode), CPS$State, mean) > 0.3)
table(tapply(is.na(CPS$MetroAreaCode), CPS$State, mean) > 0.3)
summary(MAC_S)
str(MAC_S)
MAC_S = tapply(is.na(CPS$MetroAreaCode), CPS$State, mean)
max(tapply(is.na(CPS$MetroAreaCode), CPS$State, mean))
MAC_S
tapply(is.na(CPS$MetroAreaCode), CPS$State, mean) == 1.0
sum(tapply(is.na(CPS$MetroAreaCode), CPS$State, mean) == 1.0)
table(tapply(is.na(CPS$MetroAreaCode), CPS$State, mean) == 1.0)
table(tapply(CPS$MetroAreaCode != NA, CPS$State, mean) == 1.0)
table(tapply(CPS$MetroAreaCode != "NA", CPS$State, mean) == 1.0)
table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean) >= 0.02)
table(tapply(CPS$Race == "Asian", CPS$MetroAreaCode, mean) >= 0.02)
table(tapply(CPS$Race == "Asian", CPS$MetroAreaCode, mean) >= 0.2)
sort(tapply(CPS$Education == "No high school diploma", CPS$MetroArea, mean))
tapply(CPS$Education == "No high school diploma", CPS$MetroArea, mean)
summary(CPS)
tapply(CPS$Education == "No high school diploma", CPS$MetroArea, mean)
summary(CPS)
str(CPS$Education)
summary(CPS$Education)
tapply(CPS$Education == "No high school diploma", CPS$MetroArea, mean)
summary(CPS$Education)
summary(CPS)
tapply(CPS$Education == "No high school diploma", CPS$MetroArea, mean, na.rm=TRUE)
sort(tapply(CPS$Education == "No high school diploma", CPS$MetroArea, mean, na.rm=TRUE))
summary(CPS)
tapply(CPS$Country != "United States", CPS$MetroArea, mean)
tapply(CPS$Country != "United States", CPS$MetroArea, mean, na.rm=TRUE)
sort(tapply(CPS$Country == "INDIA", CPS$MetroArea, mean, na.rm=TRUE))
sort(tapply(CPS$Country == "India", CPS$MetroArea, mean, na.rm=TRUE))
sort(tapply(CPS$Country == "Brazil", CPS$MetroArea, mean, na.rm=TRUE))
sort(tapply(CPS$Country == "Somalia", CPS$MetroArea, mean, na.rm=TRUE))
savehistory("~/Projects/edx/AnalyticsEdge_MITx15_071x/lec1/HW1_3.R")
