getwd()
USDA = read.csv("USDA.csv")
summary(USDA)
str(USDA)
max(USDA$Sodium)
max(USDA$Sodium, na.rm=TRUE)
which.max(USDA$Sodium, na.rm=TRUE)
which.max(USDA$Sodium)
max(USDA$Sodium)
names(USDA)
USDA$Description[265]
HighSodium = subset(USDA, Sodium > 10000)
nrow(HighSodium)
HighSodium$Description
match("CAVIAR", USDA$Description)
USDA$Sodium[4154]
USDA$Sodium[match("CAVIAR", USDA$Description)]
str(USDA$Sodium)
summary(USDA$Sodium)
sd(USDA$Sodium)
sd(USDA$Sodium,na.rm())
sd(USDA$Sodium,na.rm()=TRUE)
sd(USDA$Sodium,na.rm=TRUE)
plot(USDA$Protein, USDA$TotalFat)
plot(USDA$Protein, USDA$TotalFat, xlab="Protein", ylab="TotalFat")
plot(USDA$Protein, USDA$TotalFat, xlab="Protein", ylab="TotalFat", main= "Protien Vs Fat", col="red")
plot(USDA$Protein, USDA$TotalFat, xlab="Protein", ylab="TotalFat", main= "Protien Vs Fat", col="red")
plot(USDA$Protein, USDA$TotalFat, xlab="Protein", ylab="TotalFat", main= "Protien Vs Fat", col="red")
hist(USDA$VitaminC)
hist(USDA$VitaminC, xlab="Vitamin C (mg)", ylab = "Frequency")
hist(USDA$VitaminC, xlab="Vitamin C (mg)", ylab = "Frequency", main = "Histogram of Vitamin C", xlim = c(0,100))
hist(USDA$VitaminC, xlab="Vitamin C (mg)", ylab = "Frequency", main = "Histogram of Vitamin C", xlim = c(0,100), breaks=100)
hist(USDA$VitaminC, xlab="Vitamin C (mg)", ylab = "Frequency", main = "Histogram of Vitamin C", xlim = c(0,100))
hist(USDA$VitaminC, xlab="Vitamin C (mg)", ylab = "Frequency")
hist(USDA$VitaminC, xlab="Vitamin C (mg)", ylab = "Frequency", main = "Histogram of Vitamin C", xlim = c(0,100), breaks=100)
hist(USDA$VitaminC, xlab="Vitamin C (mg)", ylab = "Frequency", main = "Histogram of Vitamin C", xlim = c(0,100), breaks=2000)
hist(USDA$VitaminC, xlab="Vitamin C (mg)", ylab = "Frequency", main = "Histogram of Vitamin C", breaks=2000)
hist(USDA$VitaminC, xlab="Vitamin C (mg)", ylab = "Frequency", main = "Histogram of Vitamin C", xlim = c(0,100), breaks=2000)
boxplot(USDA$Sugar, main="Boxplot of Sugar Levels")
boxplot(USDA$Sugar, main="Boxplot of Sugar Levels", ylab = "Sugar in gms")
USDA$Sodium[1] > mean(USDA$Sodium, na.rm=TRUE)
USDA$Sodium[2] > mean(USDA$Sodium, na.rm=TRUE)
USDA$Sodium[50] > mean(USDA$Sodium, na.rm=TRUE)
HighSodium = USDA$Sodium > mean(USDA$Sodium, na.rm=TRUE)
str(HighSodium)
summary(HighSodium)
HighSodium = as.numeric(USDA$Sodium > mean(USDA$Sodium, na.rm=TRUE))
HighSodium = as.numeric(USDA$Sodium > mean(USDA$Sodium, na.rm=TRUE))
HighSodium = as.numeric(USDA$Sodium > mean(USDA$Sodium, na.rm=TRUE))
str(HighSodium)
summary(HighSodium)
USDA$HighSodium = as.numeric(USDA$Sodium > mean(USDA$Sodium, na.rm=TRUE))
str(USDA)
USDA$HighProtein = as.numeric(USDA$Protein > mean(USDA$Protein, na.rm=TRUE))
USDA$HighTotalFat = as.numeric(USDA$TotalFat > mean(USDA$TotalFat, na.rm=TRUE))
USDA$HighCarbohydrate = as.numeric(USDA$Carbohydrate > mean(USDA$Carbohydrate, na.rm=TRUE))
str(USDA)
table(USDA$HighSodium)
table(USDA$HighSodium, USDA$HighTotalFat)
tapply(USDA$Iron, USDA$HighProtein, mean, na.rm=TRUE)
tapply(USDA$VitaminC, USDA$HighCarbohydrate, mean, na.rm=TRUE)
tapply(USDA$Protien, USDA$HighCarbohydrate, mean, na.rm=TRUE)
tapply(USDA$Protein, USDA$HighCarbohydrate, mean, na.rm=TRUE)
tapply(USDA$VitaminC, USDA$HighCarbohydrate, summary, na.rm=TRUE)
?read.table
?read.csv
savehistory("~/Projects/edx/AnalyticsEdge_MITx15_071x/lec1/lab2.R")
