airlines = read.csv("AirlinesCluster.csv")
str(airlines)
summary(airlines)
preproc = preProcess(airlines)
airlinesNorm = predict(preproc, airlines)
distances = dist(airlinesNorm, method = "euclidean")
airNormHClust = hclust(distances, method="ward.D")
plot(airNormHClust)
airlineClusters = cutree(airNormHClust, k = 5)
lapply(seq(1,5,1), function(x) colMeans(subset(airlines, airlineClusters==x)))
set.seed(88)
airKMC = kmeans(airlinesNorm, centers = 5, iter.max = 1000)
str(airKMC)
airKMC$centers
lapply(split(airlines, airKMC$cluster), colMeans)
rm(split)
lapply(split(airlines, airNormHClust), colMeans)
lapply(seq(1,5,1), function(x) colMeans(subset(airlines, airlineClusters==x)))
savehistory("~/Projects/edx/AnalyticsEdge_MITx15_071x/lec6/HW2.R")
