statedata = cbind(data.frame(state.x77), state.abb, state.area, state.center,  state.division, state.name, state.region)
str(statedata)
plot(statedata$x, statedata$y)
plot(statedata$y, statedata$x)
tapply(statedata$HS.Grad, statedata$state.region, mean)
boxplot(statedata$Murder)
?boxplot
boxplot(statedata$Murder, statedata$state.region)
summary(statedata)
boxplot(statedata$Murder ~ statedata$state.region)
tapply(statedata$Murder, statedata$state.region, max)
subset(statedata, state.region == "Northeast")
lfeExpReg = lm(Life.Exp ~., data=statedata)
summary(lfeExpReg)
lfeExpReg = lm(Life.Exp ~ Population+Income +Illiteracy+Murder+HS.Grad +Frost + Area, data=statedata)
summary(lfeExpReg)
plot(statedata$Life.Exp, statedata$Income)
plot(statedata$Income, statedata$Life.Exp)
cor(statedata$Income, statedata$Life.Exp)
cor(statedata)
lfeExpReg1 = lm(Life.Exp ~ Population+Murder+HS.Grad +Frost, data=statedata)
summary(lfeExpReg1)
predD = perdict(lfeExpReg1)
predD = predict(lfeExpReg1)
predD
min(predD)
sort(predD)
min(statedata$Life.Exp)
which(min(statedata$Life.Exp))
min(statedata$Life.Exp)
sort(statedata$Life.Exp)
subset(statedata, Life.Exp == min(statedata$Life.Exp))
subset(statedata, Life.Exp == max(statedata$Life.Exp))
statedata$Life.Exp - predD
sort(statedata$Life.Exp - predD)
savehistory("~/Projects/edx/AnalyticsEdge_MITx15_071x/lec2/HW4.R")
