setwd("~/Projects/edx/AnalyticsEdge_MITx15_071x/lec3")
songs = read.csv("songs.csv")
str(songs)
summary(songs)
nrow(subset(songs,year==2010))
nrow(subset(songs,artistname=="Michael Jackson"))
mjsongs = subset(songs,artistname=="Michael Jackson")
table(mjsongs$Top10)
table(mjsongs$Top10, mjsongs$songtitle)
mjsongs
mjsongs[c("songtitle", "Top10")]
summary(songs$timesignature)
raaply(songs, function(x)unique(x))
rapply(songs, function(x)unique(x))
rapply(songs$timesignature, function(x)unique(x))
unique(songs$timesignature)
?unique
table(songs$timesignature)
summary(songs$tempo)
str(songs$tempo)
max(songs$tempo)
subset(songs, tempo == 244.30)
subset(songs, tempo >= 244.30)
subset(songs, tempo >= max(songs$tempo))
subset(songs, tempo == max(songs$tempo))
train = subset(songs,year<=2009)
test = subset(songs,year==2010)
str(train)
str(test)
nonvars = c("year", "songtitle", "artistname", "songID", "artistID")
train = train[ , !(names(train) %in% nonvars) ]
test = train[ , !(names(test) %in% nonvars) ]
test = test[ , !(names(test) %in% nonvars) ]
str(train)
str(test)
log1 = glm(Top10 ~ ., data=train, family=binomial)
summary(train)
summary(log1)
cor(train[c("loudness","energy")])
log2 = glm(Top10 ~ .-loudness, data=train, family=binomial)
summary(log2)
log3 = glm(Top10 ~ .-energy, data=train, family=binomial)
summary(log3)
pred = predict(log3, newdata = train, type="response")
table(train$Top10, pred > 0.5)
table(train$Top10, pred > 0.45)
(5953 + 248)/(5953+248+812+188)
(5953+248+812+188)
(5953 + 248)/(5953+248+812+188)
table(train$Top10, pred >= 0.45)
pred = predict(log3, newdata = test, type="response")
table(test$Top10, pred >= 0.45)
328/(328+45)
table(songs$Top10)
table(train$Top10)
table(test$Top10)
314/(314/59)
table(test$Top10, pred >= 0.45)
19/(309+19+45)
309/(309+19+45)
19/59
309/314
savehistory("~/Projects/edx/AnalyticsEdge_MITx15_071x/lec3/HW1.R")
