setwd("~/Projects/edx/AnalyticsEdge_MITx15_071x/lec3")
parole = read.csv("parole.csv")
str(parole)
parole$state = as.factor(parole$state)
parole$crime = as.factor(parole$crime)
summary(parole)
library(caTools)
str(parole)
set.seed(144)
split = sample.split(parole$violator, SplitRatio = 0.7)
train = subset(parole, split == TRUE)
test = subset(parole, split == FALSE)
log1 = glm(violator~., data=train, family="binomial")
summary(log1)
exp(1.61)
parole1 = parole[1,]
parole1
parole1[3] = 50
parole1[5] = 3
parole1[6] = 12
parole1[8] = factor(2, levels=c("1","2","3","4"))
str(parole1)
str(parole1)
str(parole)
p1 = predict(log1, newdata=parole1, type="response")
p1
p1/(1-p1)
p2 = predict(log1, newdata=test, type="response")
max(p2)
table(test$violator, p2 > 0.5)
12/23
167/179
179/(179 + 23)
table(parole$violator)
78/(78+597)
table(train$violator)
55/(418+55)
table(test$violator)
55/(179+23)
nrow(parole)
nrow(test)
nrow(train)
23/179
library(ROCR)
pTrain = predict(log1, type="response")
summary(predictTrain)
summary(pTrain)
ROCRpred = prediction(pTrain, train$violator)
ROCRperf = performance(ROCRpred, "tpr", "fpr")
plot(ROCRperf, colorize=TRUE)
plot(ROCRperf, colorize=TRUE, print.cutoffs.at=seq(0,1,by=0.1), text.adj=c(-0.2,1.7))
table(test$violator)
table(test$violator, p2 > 0.5)
table(test$violator, p2 > 0.4)
table(test$violator, p2 > 0.3)
ROCRp2 = prediction(p2, test$violator)
as.numeric(performance(ROCRp2, "auc")@y.values)
savehistory("~/Projects/edx/AnalyticsEdge_MITx15_071x/lec3/HW3.R")
