setwd("~/Projects/edx/AnalyticsEdge_MITx15_071x/lec3")
baseball = read.csv("baseball.csv")
str(baseball)
table(baseball$Year)
unique(baseball$Year)
length(unique(baseball$Year))
baseball = subset(baseball, Playoffs == 1)
str(baseball)
table(baseball$Team, baseball$Playoffs)
table(baseball$Team, baseball$RankPlayoffs)
table(baseball$Team, baseball$G)
table(baseball$Year)
PlayoffTable = table(baseball$Year)
PlayoffTable
names(PlayoffTable)
baseball$NumCompetitors = PlayoffTable[as.character(baseball$Year)]
table(baseball$NumCompetitors)
baseball$WorldSeries = as.numeric(baseball$RankPlayoffs == 1)
table(baseball$WorldSeries)
log1 = glm(WorldSeries~., data=baseball, family=binomial)
summary(log1)
log1 = glm(WorldSeries~.-Team, data=baseball, family=binomial)
summary(log1)
str(baseball)
summary(baseball)
log1 = glm(WorldSeries~Team, data=baseball, family=binomial)
summary(log1)
log2 = glm(WorldSeries~Year, data=baseball, family=binomial)
summary(log2)
log3 = glm(WorldSeries~RS, data=baseball, family=binomial)
summary(log3)
log4 = glm(WorldSeries~RA, data=baseball, family=binomial)
summary(log4)
log5 = glm(WorldSeries~W, data=baseball, family=binomial)
summary(log5)
log6 = glm(WorldSeries~OBP, data=baseball, family=binomial)
summary(log6)
log7 = glm(WorldSeries~SLG, data=baseball, family=binomial)
summary(log76)
summary(log7)
log8 = glm(WorldSeries~BA, data=baseball, family=binomial)
summary(log8)
log9 = glm(WorldSeries~RankSeason, data=baseball, family=binomial)
summary(log9)
log10 = glm(WorldSeries~OOBP, data=baseball, family=binomial)
summary(log10)
log11 = glm(WorldSeries~OSLG, data=baseball, family=binomial)
summary(log11)
log12 = glm(WorldSeries~League, data=baseball, family=binomial)
summary(log12)
log13 = glm(WorldSeries~NumCompetitors, data=baseball, family=binomial)
summary(log13)
log14 = glm(WorldSeries~Year+RA+RankSeason+NumCompetitors, data=baseball, family=binomial)
summary(log14)
cor(baseball[c("Year","RA","RankSeason","NumCompetitors")])
mlog1 = glm(WorldSeries~Year+RA, data=baseball, family=binomial)
mlog2 = glm(WorldSeries~Year+RankSeason, data=baseball, family=binomial)
mlog3 = glm(WorldSeries~Year+NumCompetitors, data=baseball, family=binomial)
mlog4 = glm(WorldSeries~RA+RankSeason, data=baseball, family=binomial)
mlog5 = glm(WorldSeries~RA+NumCompetitors, data=baseball, family=binomial)
mlog6 = glm(WorldSeries~RankSeason+NumCompetitors, data=baseball, family=binomial)
summary(mlog1)
summary(mlog2)
summary(mlog3)
summary(mlog4)
summary(mlog5)
summary(mlog6)
savehistory("~/Projects/edx/AnalyticsEdge_MITx15_071x/lec3/HW4.R")
